package com.educationerp.reporting.entity;

import com.educationerp.core.entity.BaseEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Report entity for the Education ERP System
 * Represents generated reports and analytics
 * 
 * @author Education ERP Team
 * @version 1.0.0
 */
@Entity
@Table(name = "reports", 
       uniqueConstraints = {
           @UniqueConstraint(columnNames = {"institution_id", "report_code"})
       })
public class Report extends BaseEntity {

    @NotNull(message = "Institution ID is required")
    @Column(name = "institution_id", nullable = false)
    private Long institutionId;

    @Column(name = "branch_id")
    private Long branchId;

    @NotBlank(message = "Report code is required")
    @Size(max = 50, message = "Report code must not exceed 50 characters")
    @Column(name = "report_code", nullable = false, length = 50)
    private String reportCode;

    @NotBlank(message = "Report name is required")
    @Size(max = 200, message = "Report name must not exceed 200 characters")
    @Column(name = "report_name", nullable = false, length = 200)
    private String reportName;

    @Size(max = 1000, message = "Description must not exceed 1000 characters")
    @Column(name = "description", length = 1000)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "report_type", nullable = false)
    private ReportType reportType = ReportType.STANDARD;

    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false)
    private ReportCategory category = ReportCategory.STUDENT;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private ReportStatus status = ReportStatus.ACTIVE;

    @Column(name = "is_scheduled", nullable = false)
    private Boolean isScheduled = false;

    @Column(name = "schedule_cron")
    private String scheduleCron;

    @Column(name = "last_generated_date")
    private LocalDateTime lastGeneratedDate;

    @Column(name = "next_scheduled_date")
    private LocalDateTime nextScheduledDate;

    @Size(max = 100, message = "Generated by must not exceed 100 characters")
    @Column(name = "generated_by", length = 100)
    private String generatedBy;

    @Column(name = "generation_time_ms")
    private Long generationTimeMs;

    @Column(name = "record_count")
    private Long recordCount;

    @Size(max = 500, message = "File path must not exceed 500 characters")
    @Column(name = "file_path", length = 500)
    private String filePath;

    @Size(max = 50, message = "File format must not exceed 50 characters")
    @Column(name = "file_format", length = 50)
    private String fileFormat;

    @Column(name = "file_size_bytes")
    private Long fileSizeBytes;

    @Size(max = 1000, message = "Parameters must not exceed 1000 characters")
    @Column(name = "parameters", length = 1000)
    private String parameters;

    @Size(max = 1000, message = "Filters must not exceed 1000 characters")
    @Column(name = "filters", length = 1000)
    private String filters;

    @Size(max = 1000, message = "Columns must not exceed 1000 characters")
    @Column(name = "columns", length = 1000)
    private String columns;

    @Size(max = 100, message = "Sort order must not exceed 100 characters")
    @Column(name = "sort_order", length = 100)
    private String sortOrder;

    @Column(name = "is_public", nullable = false)
    private Boolean isPublic = false;

    @Size(max = 1000, message = "Access roles must not exceed 1000 characters")
    @Column(name = "access_roles", length = 1000)
    private String accessRoles;

    @Size(max = 1000, message = "Notes must not exceed 1000 characters")
    @Column(name = "notes", length = 1000)
    private String notes;

    // Constructors
    public Report() {
    }

    public Report(Long institutionId, Long branchId, String reportCode, String reportName, 
                 String description, ReportType reportType, ReportCategory category, 
                 ReportStatus status, Boolean isScheduled, String scheduleCron) {
        this.institutionId = institutionId;
        this.branchId = branchId;
        this.reportCode = reportCode;
        this.reportName = reportName;
        this.description = description;
        this.reportType = reportType;
        this.category = category;
        this.status = status;
        this.isScheduled = isScheduled;
        this.scheduleCron = scheduleCron;
    }

    // Getters and Setters
    public Long getInstitutionId() {
        return institutionId;
    }

    public void setInstitutionId(Long institutionId) {
        this.institutionId = institutionId;
    }

    public Long getBranchId() {
        return branchId;
    }

    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    public String getReportCode() {
        return reportCode;
    }

    public void setReportCode(String reportCode) {
        this.reportCode = reportCode;
    }

    public String getReportName() {
        return reportName;
    }

    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ReportType getReportType() {
        return reportType;
    }

    public void setReportType(ReportType reportType) {
        this.reportType = reportType;
    }

    public ReportCategory getCategory() {
        return category;
    }

    public void setCategory(ReportCategory category) {
        this.category = category;
    }

    public ReportStatus getStatus() {
        return status;
    }

    public void setStatus(ReportStatus status) {
        this.status = status;
    }

    public Boolean getIsScheduled() {
        return isScheduled;
    }

    public void setIsScheduled(Boolean isScheduled) {
        this.isScheduled = isScheduled;
    }

    public String getScheduleCron() {
        return scheduleCron;
    }

    public void setScheduleCron(String scheduleCron) {
        this.scheduleCron = scheduleCron;
    }

    public LocalDateTime getLastGeneratedDate() {
        return lastGeneratedDate;
    }

    public void setLastGeneratedDate(LocalDateTime lastGeneratedDate) {
        this.lastGeneratedDate = lastGeneratedDate;
    }

    public LocalDateTime getNextScheduledDate() {
        return nextScheduledDate;
    }

    public void setNextScheduledDate(LocalDateTime nextScheduledDate) {
        this.nextScheduledDate = nextScheduledDate;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public Long getGenerationTimeMs() {
        return generationTimeMs;
    }

    public void setGenerationTimeMs(Long generationTimeMs) {
        this.generationTimeMs = generationTimeMs;
    }

    public Long getRecordCount() {
        return recordCount;
    }

    public void setRecordCount(Long recordCount) {
        this.recordCount = recordCount;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getFileFormat() {
        return fileFormat;
    }

    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat;
    }

    public Long getFileSizeBytes() {
        return fileSizeBytes;
    }

    public void setFileSizeBytes(Long fileSizeBytes) {
        this.fileSizeBytes = fileSizeBytes;
    }

    public String getParameters() {
        return parameters;
    }

    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

    public String getFilters() {
        return filters;
    }

    public void setFilters(String filters) {
        this.filters = filters;
    }

    public String getColumns() {
        return columns;
    }

    public void setColumns(String columns) {
        this.columns = columns;
    }

    public String getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Boolean getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    public String getAccessRoles() {
        return accessRoles;
    }

    public void setAccessRoles(String accessRoles) {
        this.accessRoles = accessRoles;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    // Business methods
    public boolean isActive() {
        return status == ReportStatus.ACTIVE && getIsActive();
    }

    public boolean isScheduled() {
        return isScheduled != null && isScheduled;
    }

    public boolean isPublic() {
        return isPublic != null && isPublic;
    }

    public void markAsGenerated(String generatedBy, Long generationTimeMs, Long recordCount, 
                               String filePath, String fileFormat, Long fileSizeBytes) {
        this.lastGeneratedDate = LocalDateTime.now();
        this.generatedBy = generatedBy;
        this.generationTimeMs = generationTimeMs;
        this.recordCount = recordCount;
        this.filePath = filePath;
        this.fileFormat = fileFormat;
        this.fileSizeBytes = fileSizeBytes;
    }

    public void activate() {
        this.status = ReportStatus.ACTIVE;
    }

    public void deactivate() {
        this.status = ReportStatus.INACTIVE;
    }

    public void archive() {
        this.status = ReportStatus.ARCHIVED;
    }

    // Enums
    public enum ReportType {
        STANDARD, CUSTOM, SCHEDULED, AD_HOC, DASHBOARD, ANALYTICS
    }

    public enum ReportCategory {
        STUDENT, COURSE, PAYMENT, INVENTORY, USER, INSTITUTION, FINANCIAL, ACADEMIC, 
        ATTENDANCE, EXAM, GRADES, ENROLLMENT, REPORTS, SYSTEM
    }

    public enum ReportStatus {
        ACTIVE, INACTIVE, ARCHIVED, DRAFT, GENERATING, ERROR
    }

    // equals, hashCode, and toString
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        Report report = (Report) o;
        return Objects.equals(institutionId, report.institutionId) &&
                Objects.equals(reportCode, report.reportCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), institutionId, reportCode);
    }

    @Override
    public String toString() {
        return "Report{" +
                "id=" + getId() +
                ", institutionId=" + institutionId +
                ", reportCode='" + reportCode + '\'' +
                ", reportName='" + reportName + '\'' +
                ", reportType=" + reportType +
                ", category=" + category +
                ", status=" + status +
                ", isActive=" + getIsActive() +
                '}';
    }
}
